#:schema node_modules/wrangler/config-schema.json
name = "sublink-workers"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1bafa66542714682b13dc9935fd2b261" }
]

[assets]
directory = "./public"
